In [1]:
import numpy as np

# Numpy array

In [2]:
benimlistem=[20,30,40]# liste olarak tanimliyorm

In [3]:
type(benimlistem) # liste

list

In [4]:
np.array(benimlistem)#liste olarak tanimladigimi numpy dizisine cevirebilmek ici

array([20, 30, 40])

In [6]:
type(np.array(benimlistem)) #turunu gostermek icin yaptim

numpy.ndarray

In [7]:
matrixListesi=[[10,20,30],[20,30,40],[30,40,50]]

In [8]:
type(matrixListesi)

list

In [10]:
np.array(matrixListesi) #listeyi gercek matrix gorunumune ceviriyoor

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# arange

In [12]:
list(range(0,10)) # liste dizisi

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
np.arange(0,10) #numpy dizisi

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,10,2) #( kactan basliyor , kactanbitiyor , kacar kacar gidiyor )

array([0, 2, 4, 6, 8])

# zeros

In [20]:
np.zeros(5) #icersi tamamen sıfır olan dizi olusturuyor (diziuzunlugu)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,3)) #matrix gorunum icin " ((iki parantez icine yazilir)) ""

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones(10) #icerisi tamamen bir olan dizi olusturuyor(dizi uzunlugu)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.ones((5,5)) #matrix gorunum icin " ((iki parantez icine yazilir)) ""

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Linspace

In [31]:
np.linspace(0,20,5)#"0 ile 20 arasinda 5 sayi sec (o 5 sayilarin birbirine uzaklıgı sabit olsun )"
#hepsinin arasinda 5 fark var

array([ 0.,  5., 10., 15., 20.])

In [33]:
np.linspace(0,20,6)#"0 ile 20 arasinda 6 sayi sec (o 6 sayilarin birbirine uzaklıgı sabit olsun )"
#hepsinin arasinda 4 fark var 

array([ 0.,  4.,  8., 12., 16., 20.])

# eye

In [36]:
np.eye(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Numpy Random

In [39]:
np.random.randn(4)#randn= bize tek bir deger degil dizi dönduruyor

array([ 0.65057816, -0.17593981,  0.52253972, -0.10288363])

In [40]:
np.random.randn(4,4)

array([[-2.41744097e-04, -6.68302694e-01, -4.24477990e-01,
        -9.73551440e-01],
       [ 8.22325483e-01, -3.89845889e-01, -1.93065148e+00,
         1.99876450e+00],
       [-6.96942321e-01, -3.91039757e-03, -1.54178652e+00,
         1.41441448e-02],
       [ 3.01677375e-01,  4.70180173e-01,  2.20239580e-02,
        -4.59941177e-01]])

In [42]:
np.random.randint(1,10) #randint= tek bir deger veriyor

2

In [43]:
np.random.randint(1,10,5)#1 ve 10 arasında 10 dahil degil iken 5 deger verir

array([3, 8, 9, 4, 8])

In [48]:
BenimNumpyDizim=np.arange(30)#numpy dizisi

In [49]:
BenimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [52]:
BenimRandomDizim=np.random.randint(0,100,20)

In [53]:
BenimRandomDizim

array([ 1, 28, 90, 42, 99, 83, 20, 25, 82, 74, 34, 74, 23, 62, 19, 12, 70,
       72, 58, 59])

# Numpy dizi Methodlari

In [69]:
BenimNumpyDizim.reshape(6,5) #5 sira 6 kolon olusturur

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [57]:
BenimNumpyDizim.max()#29 a kadar

29

In [59]:
BenimRandomDizim.max()#99 a kadar

99

In [61]:
BenimNumpyDizim.min()# en az kaca

0

In [62]:
BenimRandomDizim.min()# en az kaca

1

In [67]:
BenimRandomDizim.argmax()

4

In [66]:
BenimRandomDizim.argmin() # ilk en kucuk harf

0

In [68]:
BenimNumpyDizim.shape # method vs olmadıgı icin parantez konmaz  

(30,)