In [2]:
import numpy as np

In [3]:
Dizim=np.arange(0,15) # 0 dan 15 e kadar dizi olusturur

In [4]:
Dizim 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
Dizim[5]

5

In [6]:
Dizim[3:5] #3. indeks ile 5. indeks arasini  aliyor

array([3, 4])

In [7]:
Dizim[3:5]=-5 #dizimdeki 3 ile 5 arasindakileri -5 yapti

In [8]:
Dizim

array([ 0,  1,  2, -5, -5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
dizi=np.arange(0,24) # 0 dan 24 e kadar dizi olusturur

In [10]:
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
slicingDizisi=dizi[4:9] #slicingDizisine 4 ile 9 arasindakileri aliyor

In [12]:
slicingDizisi # 4 ile 9 arasindakileri aliyor

array([4, 5, 6, 7, 8])

In [13]:
dizi # normal dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
#slicingDizisi=700  # diziyi 700 e esitlenir

In [15]:
slicingDizisi[:]=700 #slicing dizi icindekilerin butun ogeleri 700 e esitliyor

In [16]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [17]:
dizi   #slicing dizisini normal dizinin icindeki sayilari alsiin denmisti 
#ondan dolayi icerisindeki sayilari 700 yapti 

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [18]:
ornek=np.arange(0,24)

In [19]:
ornek

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
ornekkopya=ornek.copy()

In [21]:
ornekkopya

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

Yukaridaki olustudugumuz ornek dizinin ".copy()" ile baska bir dizi olusturduk ve icerisine kopyaladik bu sayede ayri diziler oldu 

In [22]:
ornekkopyaslicing=ornekkopya[3:6]

In [23]:
ornekkopyaslicing[:] = 1000

In [24]:
ornekkopyaslicing

array([1000, 1000, 1000])

In [25]:
ornekkopya #slicing ile icersinde belirli dizeleri 1000 e esitledik 

array([   0,    1,    2, 1000, 1000, 1000,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [26]:
ornek #ancak ornekkopya ile ornek ayri diziler oldugu icin ornek de herhangi bir degisiklik olmadi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# Matrix

In [27]:
# tek boyutlu dizileri 2 boyutlu yapacagiz

In [28]:
ornekliste=[[10,20,30],[40,50,60],[70,80,90]] # once liste olusturduk 

In [29]:
ornekmatrixdizi=np.array(ornekliste) #olusturugumuz listeyi matrix e ornekledik

In [30]:
ornekmatrixdizi

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [31]:
ornekmatrixdizi[0] #ornek matrixin 0. ogesini istiyoruz

array([10, 20, 30])

In [32]:
ornekmatrixdizi[0][1] #0. ogenin 1. ogesinin verdi 

20

In [33]:
ornekmatrixdizi[0,1]  #0. ogenin 1. ogesinin verdi  ayni sey ustteki ile

20

In [34]:
ornekmatrixdizi[1:,2] # 1. ogenin 

array([60, 90])

In [35]:
ornekmatrixdizi[2:,2:]

array([[90]])

In [36]:
yeniliste=[[0,1,2,3,4],[5,6,7,8,9],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]#dizilerin iclerindeki ogelerin adedi birbirine esit olmali

In [37]:
yenimatrix=np.array(yeniliste)

In [38]:
yenimatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
yenimatrix[2]#0. dizi dahil 2. diziyi (bize göre 3. diziyi ) getiriyor

array([11, 12, 13, 14, 15])

In [40]:
yenimatrix[[0,2,4]] #"0. diziyi 2. diziyi ve 4. diziyi cagirir"

array([[ 0,  1,  2,  3,  4],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [41]:
yenimatrix[[4,2,0]] #cagirma sirasina gore dizileri cagiriyor

array([[21, 22, 23, 24, 25],
       [11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4]])

# Operasyonlar


In [42]:
yenibirdizi=np.random.randint(1,100,20)

In [43]:
yenibirdizi

array([52, 45, 59, 18, 85, 38, 88, 99, 60, 79, 59,  9,  5,  8, 16, 20, 66,
        8, 76,  7])

In [44]:
yenibirdizi>24 # 24 den buyuk rastgele sayilari True kucukleri False ile acik acik belirtiyor(ustteki siraya gore)

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False,  True, False,
        True, False])

In [45]:
yenibirdizi # yapilan true-False dan sonra herhangi bir degisiklik yapmiyor

array([52, 45, 59, 18, 85, 38, 88, 99, 60, 79, 59,  9,  5,  8, 16, 20, 66,
        8, 76,  7])

In [46]:
sonuc=yenibirdizi<24 #dizinin icindeki 24 den buyuk sayilari sonuc dizesine booleon tipinde true-false 
#tipinde atar

In [47]:
sonuc

array([False, False, False,  True, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True, False,  True,
       False,  True])

In [48]:
yenibirdizi[sonuc]#Booleon tipinde olan sayilarin sadece true olanlari sayi olarak bize gosteriyor

array([18,  9,  5,  8, 16, 20,  8,  7])

In [49]:
yenibirdizi # hala degismedi

array([52, 45, 59, 18, 85, 38, 88, 99, 60, 79, 59,  9,  5,  8, 16, 20, 66,
        8, 76,  7])

In [50]:
yenibirdizi[yenibirdizi<24]#boyle de siralayabiliriz

array([18,  9,  5,  8, 16, 20,  8,  7])

In [51]:
sondizi=np.arange(0,24)

In [52]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [53]:
sondizi+sondizi #iki kattini verir dizileri kendi icersinde toplayabilir

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [54]:
sondizi*sondizi#kendi icersinde carpilabilir

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [55]:
sondizi-sondizi # cikarilirsa her zaman 0 olur

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [56]:
sondizi/sondizi #hata verir ayri yetten hepsinin cevabi 1 olur (hata sebebi 0 ı 0 a bolmek)

<ipython-input-56-434202db4048>:1: RuntimeWarning: invalid value encountered in true_divide
  sondizi/sondizi #hata verir ayri yetten hepsinin cevabi 1 olur (hata sebebi 0 ı 0 a bolmek)


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [57]:
np.sqrt(sondizi) #dizi icersindeki tum degerlerin karekokunu alir

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [59]:
np.max(sondizi) # maximum degerini getirir

23

In [61]:
np.min(sondizi) # minimum degerini getirir

0